### ISSUE TITLE
launching python3 -m cli - server.so: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by FrancescoScappatura** [developer-foundry/diminish#36]
Hi,
how can I obtain the server.so library?
I didn't found any command for building it.
Thanks

**Comment by foundrium** [comment]
@FrancescoScappatura Thanks for reaching out. If you checkout https://github.com/developer-foundry/diminish/blob/master/tasks.py you will see we have a python task using the python library `invoke` to execute the necessary `gcc` compile command that creates the `server.so`. You can create the `server.so` by running `invoke build-libraries` (this assumes you have python3, pip3, and run the pip3 command to install invoke). If you prefer to work directly with `gcc` though you can just copy out the build commands from the file linked above.

**Comment by FrancescoScappatura** [comment]
Thanks a lot.
Sorry I miss it.

**Comment by foundrium** [comment]
No worries, glad to help. Let us know if you have any other questions.
